import { access, readFile, readdir, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const categoryPairs = [
  ["all", "All"],
  ["landing-pages", "Landing pages"],
  ["hero-sections", "Hero sections"],
  ["animations-loaders", "Animations & loaders"],
  ["portfolios", "Portfolios"],
  ["components-ui", "Components & UI"],
];

const exists = async (file) => {
  try {
    await access(file, constants.F_OK);
    return true;
  } catch {
    return false;
  }
};

const cleanMarkdown = (value) =>
  value
    .replace(/<[^>]+>/g, "")
    .replace(/\*\*/g, "")
    .replace(/`/g, "")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .trim();

const titleFromSlug = (slug) =>
  slug
    .replace(/-h\d+$/, "")
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");

const projects = [];

for (const [category, label] of categoryPairs.slice(1)) {
  const categoryPath = path.join(root, category);
  if (!(await exists(categoryPath))) {
    console.warn(`Skipping missing category directory: ${category}`);
    continue;
  }
  const entries = (await readdir(categoryPath, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith("."))
    .sort((a, b) => a.name.localeCompare(b.name));

  const metadata = new Map();
  const categoryReadme = path.join(categoryPath, "README.md");
  if (await exists(categoryReadme)) {
    const source = await readFile(categoryReadme, "utf8");
    for (const line of source.split("\n")) {
      const match = line.match(
        /^\|\s*\[([^\]]+)\]\([^)]+\)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*$/,
      );
      if (match) {
        metadata.set(match[1], {
          description: cleanMarkdown(match[2]),
          stack: cleanMarkdown(match[3]),
        });
      }
    }
  }

  for (const entry of entries) {
    const slug = entry.name;
    const projectPath = path.join(categoryPath, slug);
    const info = metadata.get(slug) ?? {};
    const hasPackage = await exists(path.join(projectPath, "package.json"));
    const standardEntry = await exists(path.join(projectPath, "index.html"));
    const customEntry = await exists(path.join(projectPath, `${slug}.html`));
    const entrypoint = standardEntry
      ? `${category}/${slug}/index.html`
      : customEntry
        ? `${category}/${slug}/${slug}.html`
        : null;

    let title = titleFromSlug(slug);
    const readmePath = path.join(projectPath, "README.md");
    if (await exists(readmePath)) {
      const readme = await readFile(readmePath, "utf8");
      const heading = readme.match(/^#\s+(.+)$/m);
      if (heading) {
        title = cleanMarkdown(heading[1])
          .replace(/\s+\([^)]*\)\s*$/, "")
          .replace(/\s+—.*$/, "")
          .trim();
      }
    }

    projects.push({
      id: `${category}/${slug}`,
      slug,
      title,
      category,
      categoryLabel: label,
      description:
        info.description ||
        `${title} — a UI experiment from the ${label.toLowerCase()} collection.`,
      stack: info.stack || (hasPackage ? "Framework project" : "HTML, CSS, JavaScript"),
      demo: `${category}/${slug}/demo.mp4`,
      poster: `${category}/${slug}/poster.jpg`,
      readme: `${category}/${slug}/README.md`,
      entrypoint,
      directlyRunnable: Boolean(entrypoint && !hasPackage),
    });
  }
}

const categories = categoryPairs.map(([id, label]) => ({
  id,
  label,
  count: id === "all" ? projects.length : projects.filter((project) => project.category === id).length,
}));

const output = `// Generated by scripts/generate-gallery.mjs\nwindow.UI_DIRECTORY = ${JSON.stringify(
  { projects, categories },
  null,
  2,
)};\n`;

await writeFile(path.join(root, "gallery-data.js"), output);
console.log(`Generated gallery-data.js with ${projects.length} projects.`);
